deployment:
  tasks:
    - export PRIVATEPATH=/home/storylab/statamic/
    - /bin/cp -R --exclude='public' * $PRIVATEPATH
    - export PUBLICPATH=/home/storylab/public_html/
    - /bin/cp -R public/* $PUBLICPATH
